#! /usr/bin/env python
# -*- coding:Utf8 -*-

class Config(object):
	def __init__(self, filename):
		self.filename = filename

		self.InitCondFile              = None
		self.OutputDir                 = None
		self.EnergyFile                = "energy.log"
		self.InfoFile                  = "info.log"
		self.TimingsFile               = "timings.log"
		self.CpuFile                   = "cpu.log"
		self.RestartFile               = "restart"
		self.SnapshotFileBase          = None
		self.OutputListFilename        = None
		self.NumFilesPerSnapshot       = 1
		self.NumFilesWrittenInParallel = 1
		self.ICFormat                  = 1
		self.SnapFormat                = 1
		self.TimeLimitCPU              = 72000
		self.ResubmitOn                = 0
		self.ResubmitCommand           = None
		self.CpuTimeBetRestartFile     = 72000
		self.ComovingIntegrationOn     = 0
		self.TypeOfTimestepCriterion   = 0
		self.OutputListOn              = 0
		self.PeriodicBoundariesOn      = 0
		self.TimeBegin                 = 0.0
		self.TimeMax                   = 1.0
		self.Omega0                    = 0.
		self.OmegaLambda               = 0.
		self.OmegaBaryon               = 0.
		self.HubbleParam               = 0.
		self.BoxSize                   = 0.
		self.TimeBetSnapshot           = 0.1
		self.TimeOfFirstSnapshot       = 0.1
		self.TimeBetStatistics         = 0.05
		self.ErrTolIntAccuracy         = 0.025
		self.MaxRMSDisplacementFac     = 0.2
		self.CourantFac                = 0.15
		self.MaxSizeTimestep           = 1e-5
		self.MinSizeTimestep           = 0.
		self.ErrTolTheta               = 0.5
		self.TypeOfOpeningCriterion    = 1
		self.ErrTolForceAcc            = 0.005
		self.TreeDomainUpdateFrequency = 0.1
		self.DesNumNgb                 = 0
		self.ArtBulkViscConst          = 0.0
		self.MaxNumNgbDeviation        = 0
		self.InitGasTemp               = 0
		self.MinGasTemp                = 0
		self.PartAllocFactor           = 30.0
		self.TreeAllocFactor           = 5.0
		self.BufferSize                = 30
		self.UnitLength_in_cm          = None
		self.UnitMass_in_g             = None
		self.UnitVelocity_in_cm_per_s  = None
		self.GravityConstantInternal   = 0
		self.MinGasHsmlFractional      = 0.25
		self.SofteningGas              = None
		self.SofteningHalo             = None
		self.SofteningDisk             = None
		self.SofteningBulge            = None
		self.SofteningStars            = None
		self.SofteningBndry            = None
		self.SofteningGasMaxPhys       = None
		self.SofteningHaloMaxPhys      = None
		self.SofteningDiskMaxPhys      = None
		self.SofteningBulgeMaxPhys     = None
		self.SofteningStarsMaxPhys     = None
		self.SofteningBndryMaxPhys     = None


